/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1,2,3,5,8,13,21,34,55,89,⋯
By considering the terms in the Fibonacci sequence whose values do not exceed N, find the sum of the even-valued terms.

Input Format 
First line contains T that denotes the number of test cases. This is followed by T lines, each containing an integer, N.

Output Format 
Print the required answer for each test case.

Constraints 
1≤T≤105 
10≤N≤4×1016
Sample Input

2
10
100
Sample Output

10
44
*/

package main
import "fmt"

func main() {
 //Enter your code here. Read input from STDIN. Print output to STDOUT
    var t, n, a1, a2, sum int
    fmt.Scanf("%d", &t)
    for i:=0; i<t; i++ {
        fmt.Scanf("%d", &n)
        a1, a2 = 1, 2
        sum = 0
        for a2 < n {
            if (a2 % 2) == 0 {
                sum += a2
            }
            a1, a2 = a2, (a1+a2)
        }
        fmt.Println(sum)
    }
}
